### ISSUE TITLE
No OpKernel was registered to support Op 'MaxPoolWithArgmax' 

### ISSUE THREAD

**Issue by DawnMe** [mshunshin/SegNetCMR#2]
After running python train.py, I'm getting the following error:

No OpKernel was registered to support Op 'MaxPoolWithArgmax' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

Anyone has encountered this?

Shahar

**Comment by mshunshin** [comment]
Yep - this isn't available on CPUs - you need a GPU to run this.

See: https://github.com/tensorflow/tensorflow/issues/6035

**Comment by DawnMe** [comment]
@mshunshin Thanks. Closed the issue.
